/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Speech.Api;
using Cloudmersive.APIClient.NET.Speech.Model;
using Cloudmersive.APIClient.NET.Speech.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Speech.Test
{
    /// <summary>
    ///  Class for testing SpeechRecognitionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpeechRecognitionResultTests
    {
        // TODO uncomment below to declare an instance variable for SpeechRecognitionResult
        //private SpeechRecognitionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpeechRecognitionResult
            //instance = new SpeechRecognitionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpeechRecognitionResult
        /// </summary>
        [Test]
        public void SpeechRecognitionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpeechRecognitionResult
            //Assert.IsInstanceOfType<SpeechRecognitionResult> (instance, "variable 'instance' is a SpeechRecognitionResult");
        }


        /// <summary>
        /// Test the property 'TextResult'
        /// </summary>
        [Test]
        public void TextResultTest()
        {
            // TODO unit test for the property 'TextResult'
        }

    }

}
