/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Speech.Client;
using Cloudmersive.APIClient.NET.Speech.Api;
using Cloudmersive.APIClient.NET.Speech.Model;

namespace Cloudmersive.APIClient.NET.Speech.Test
{
    /// <summary>
    ///  Class for testing RecognizeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RecognizeApiTests
    {
        private RecognizeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RecognizeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecognizeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RecognizeApi
            //Assert.IsInstanceOfType(typeof(RecognizeApi), instance, "instance is a RecognizeApi");
        }

        
        /// <summary>
        /// Test RecognizeFile
        /// </summary>
        [Test]
        public void RecognizeFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream speechFile = null;
            //var response = instance.RecognizeFile(speechFile);
            //Assert.IsInstanceOf<SpeechRecognitionResult> (response, "response is SpeechRecognitionResult");
        }
        
    }

}
