/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Speech.Client;
using Cloudmersive.APIClient.NET.Speech.Api;

namespace Cloudmersive.APIClient.NET.Speech.Test
{
    /// <summary>
    ///  Class for testing SpeakApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SpeakApiTests
    {
        private SpeakApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SpeakApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpeakApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SpeakApi
            //Assert.IsInstanceOfType(typeof(SpeakApi), instance, "instance is a SpeakApi");
        }

        
        /// <summary>
        /// Test SpeakPost
        /// </summary>
        [Test]
        public void SpeakPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string format = null;
            //string text = null;
            //var response = instance.SpeakPost(format, text);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
