/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloudmersive.APIClient.NET.Speech.Client;
using Cloudmersive.APIClient.NET.Speech.Model;

namespace Cloudmersive.APIClient.NET.Speech.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecognizeApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Recognize audio input as text using machine learning
        /// </summary>
        /// <remarks>
        /// Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>SpeechRecognitionResult</returns>
        SpeechRecognitionResult RecognizeFile (System.IO.Stream speechFile);

        /// <summary>
        /// Recognize audio input as text using machine learning
        /// </summary>
        /// <remarks>
        /// Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>ApiResponse of SpeechRecognitionResult</returns>
        ApiResponse<SpeechRecognitionResult> RecognizeFileWithHttpInfo (System.IO.Stream speechFile);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Recognize audio input as text using machine learning
        /// </summary>
        /// <remarks>
        /// Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>Task of SpeechRecognitionResult</returns>
        System.Threading.Tasks.Task<SpeechRecognitionResult> RecognizeFileAsync (System.IO.Stream speechFile);

        /// <summary>
        /// Recognize audio input as text using machine learning
        /// </summary>
        /// <remarks>
        /// Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>Task of ApiResponse (SpeechRecognitionResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpeechRecognitionResult>> RecognizeFileAsyncWithHttpInfo (System.IO.Stream speechFile);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RecognizeApi : IRecognizeApi
    {
        private Cloudmersive.APIClient.NET.Speech.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecognizeApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NET.Speech.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NET.Speech.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RecognizeApi(Cloudmersive.APIClient.NET.Speech.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NET.Speech.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NET.Speech.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.Speech.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.Speech.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Recognize audio input as text using machine learning Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>SpeechRecognitionResult</returns>
        public SpeechRecognitionResult RecognizeFile (System.IO.Stream speechFile)
        {
             ApiResponse<SpeechRecognitionResult> localVarResponse = RecognizeFileWithHttpInfo(speechFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Recognize audio input as text using machine learning Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>ApiResponse of SpeechRecognitionResult</returns>
        public ApiResponse< SpeechRecognitionResult > RecognizeFileWithHttpInfo (System.IO.Stream speechFile)
        {
            // verify the required parameter 'speechFile' is set
            if (speechFile == null)
                throw new ApiException(400, "Missing required parameter 'speechFile' when calling RecognizeApi->RecognizeFile");

            var localVarPath = "/speech/recognize/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (speechFile != null) localVarFileParams.Add("speechFile", this.Configuration.ApiClient.ParameterToFile("speechFile", speechFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecognizeFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechRecognitionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpeechRecognitionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechRecognitionResult)));
        }

        /// <summary>
        /// Recognize audio input as text using machine learning Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>Task of SpeechRecognitionResult</returns>
        public async System.Threading.Tasks.Task<SpeechRecognitionResult> RecognizeFileAsync (System.IO.Stream speechFile)
        {
             ApiResponse<SpeechRecognitionResult> localVarResponse = await RecognizeFileAsyncWithHttpInfo(speechFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Recognize audio input as text using machine learning Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="speechFile">Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.</param>
        /// <returns>Task of ApiResponse (SpeechRecognitionResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpeechRecognitionResult>> RecognizeFileAsyncWithHttpInfo (System.IO.Stream speechFile)
        {
            // verify the required parameter 'speechFile' is set
            if (speechFile == null)
                throw new ApiException(400, "Missing required parameter 'speechFile' when calling RecognizeApi->RecognizeFile");

            var localVarPath = "/speech/recognize/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (speechFile != null) localVarFileParams.Add("speechFile", this.Configuration.ApiClient.ParameterToFile("speechFile", speechFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RecognizeFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechRecognitionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpeechRecognitionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechRecognitionResult)));
        }

    }
}
